### ISSUE TITLE
Decode ASN1 Structure fails

### ISSUE THREAD

**Issue by hassfers** [leif-ibsen/ASN1#1]
Hello i would like to decode a Message in ASN1 structure. 
is it possible and how should i do this?

```swift 
ASN1Sequence.build(messageData)
ASN1.build(messageData)
```
unfortunately does not work

**Comment by leif-ibsen** [comment]
I assume your messageData is a byte array, for example

let messageData: Bytes = [48, 20, 3, 2, 3, 127, 2, 9, 0, 171, 84, 169, 140,
235, 31, 10, 210, 6, 3, 42, 3, 4]


*t**hen do*


*let* x = *try* ASN1.build(messageData)

print("asn1 =")

print(x.description)

which prints


*asn1 =*

*Sequence (3):*

*  Bit String (5): 01111*

*  Integer: 12345678901234567890*

*  Object Identifier: 1.2.3.4*



*Hope that helps*

Den man. 4. nov. 2019 kl. 12.40 skrev Stefan Haßferter <
notifications@github.com>:

**Comment by leif-ibsen** [comment]
I assume your messageData is a byte array, for example

let messageData: Bytes = [48, 20, 3, 2, 3, 127, 2, 9, 0, 171, 84, 169, 140,
235, 31, 10, 210, 6, 3, 42, 3, 4]

then do

let x = try ASN1.build(messageData)
print("asn1 =")
print(x.description)

which prints

asn1 =
Sequence(3):
  Bit String (5): 01111
  Integer: 12345678901234567890
  Object Identifier: 1.2.3.4

Hope this helps

Den man. 4. nov. 2019 kl. 16.58 skrev Leif Ibsen <leif.m.ibsen@gmail.com>:

**Comment by hassfers** [comment]
Sorry for late reply.

Yes your snippet helps. But if i want to decode an CMS-Message, which bases on ASN1-Structure, i get an exception  
```swift 
Fatal error: 'try!' expression unexpectedly raised an error: ASN1.ASN1Exception.tooLong(length: 0):
```

i want to decode this message: 

[message](https://lapo.it/asn1js/#MIAGCSqGSIb3DQEHA6CAMIACAQAxggKaMIIBSQIBAoAxS0VZU1RPUkUtSUQtMGU0ZGU1N2M5LTUxMmUtNDBjNy05ODY2LWM1MTYzZTRhNzM5YTANBgkqhkiG9w0BAQEFAASCAQAs9sDUBeHtVRKEhLCTn-_sKXlV9_bKNHFIx5bMRe8V-nV9efMs63YAhcWL-cogt-0rsYsyHNf_MvF9CUm_9iFQD9ewJ0CGmj6wUImbPdADG7EQg8q1tqYO21b5BlA_vuBfBo4RWOim-swFn4YB4JRKEHS-vtVreGoQhENU7lhuy7fY2tKiVfQb6BnDlEdhg8p68MEJf6WScv5LLWhyY0bs1QkSnQY02x7L81MFmuoTaqalxdIzAXt1S_MQfDLUNe611p56mYlJWgDa-PlxVm2wHB69bn_7UPJxETXPhYHTeg6FtQ7RdnS77BhAZjEmNWk-SHRaE-oRdWhKIH1Si2yoMIIBSQIBAoAxS0VZU1RPUkUtSUQtMGY1MWIwZjFlLWUyOTQtNDJjOC1hZjhlLTRiNmQwNmQzOGUxOTANBgkqhkiG9w0BAQEFAASCAQAtIZz_KvIHiqhfkExRqknz619TymPrlEtrZkDrLIlYd9E5gK3FutYBJvyPjn56QZ_NacAFFxHAFoeCc8hiAiKnkStOgC3PMiSTkVZHbD6ol9wrwPMneoyWtKrNnlBRAw4jylXHtsEifwhzOXzCrmFvu2Wjj9jR3_rOsjHDypubm5ZRgMxE0SGCNQYaAFM_ByU0cMSM8M4l1qdYJG_zQm0SWMPqse9Xts9GipSpOl0z6FYOEVj7V2BCpM40S2EsNarWwnqLjHfZ2S3cwmoZ2XuXVBl0cjlxSlTIzc72vN2PY9gS4gUpSvQpWAcvg0jGlym6X69QASJoOISaiDcEM8-vMIAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2RhLXaFDhYLr0nFnAgEQoIAEHAc2pvt3f_YMpbiw733hTcfyhTYHnCSM3NToynkAAAAAAAAAAAAA)

is there a possibility to decode messages with Indefinite length?

**Comment by leif-ibsen** [comment]
Your example uses indefinite length encoding. ASN1 does not support this. It only supports definite length encoding. Sorry.

**Comment by leif-ibsen** [comment]
There is a new release 1.1.0. Among other things it supports indefinite length encoding.
