### ISSUE TITLE
Crypto Review Finding #5: Lack of length validation during decoding

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/ASN1#3]
## Vulnerability details
⚠ The evaluation is based on the assumption that the library is used in a client application and only one person is affected by the crash at a time. In the context of a server application, the rating would be higher.

The basic ASN.1 decoding is implemented in the method of the class ASN1. The tag and the length are read (lines 2 to 6) and then the corresponding value. Depending on the tag type, the data is processed accordingly (from line 7). The problem is that there is no tag type specific validation of the length. The length is either used unchecked (for example, integer, line 15) or completely ignored for some tag types (for example, boolean, line 12).
 
```
static func doBuild(_ input: InputStream) throws -> ASN1 { 
    let nb = try input.nextByte() 
    let tagClass = (nb >> 6) & 0x3 
    let constructed = nb & 0x20 != 0
    let tag = try getTag(nb, input) 
    let length = try getLength(input) 
    if tagClass == 2 {
[...]     
    } else if tagClass == 0 {
        switch tag { 
            case TAG_Boolean:
              return ASN1Boolean(try input.nextByte() != 0)
[...]
            case TAG_Integer: 
              return ASN1Integer(try input.nextBytes(length))
[...]
```

Specifically, it is possible, for example, to set the length of primitive data types to INDEFINITE, which is represented internally as -1. The following test case shows this with an integer type:

```
func testIndefinteLength() throws {
  let b1: Bytes = [2, 128] // Integer of indefinite length 
  try ASN1.build(b1)
}
```
As a consequence, reading the value with many tag types results in the following fatal error and thus a crash:

```
Test Case 'ASN1Tests.testIndefinteLength' started at 2021-06-30 16:08:54.228
Swift/Range.swift:739: Fatal error: Range requires lowerBound <= upperBound 
Current stack trace:
0 libswiftCore.so 0x00007fb1554dc210 swift_reportError + 50 
1 libswiftCore.so 0x00007fb155550fc0 _swift_stdlib_reportFatalErrorInFile + 112
2 libswiftCore.so 0x00007fb15523af56 <unavailable> + 1425238
3 libswiftCore.so 0x00007fb15523ab7f <unavailable> + 1424255
4 libswiftCore.so 0x00007fb15523a91c <unavailable> + 1423644
5 libswiftCore.so 0x00007fb15523a430 _assertionFailure(_:_:file:line:flags:) 
6 ASN1PackageTests 0x00005590fd4d4f9a <unavailable> + 315290
[...]
```

## Countermeasures
We recommend implementing a validation of the length field for each tag type. In addition, the InputStream class should also perform a validation of the length parameter and throw an exception if necessary.

## References
[1] Source code of the function doBuild in the class ASN1: https://github.com/leif-ib- sen/ASN1/blob/53e0b34a34f882386e09d10d6d00bb7e969e307f/Sources/ASN1/ASN1.swif t#L304

**Comment by leif-ibsen** [comment]
Fixed in release 2.0.0. Length validation is now done thoroughly.
