### ISSUE TITLE
Crypto Review Finding #6: Precondition Crash in ASN1Integer due to empty value

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/ASN1#4]
## Vulnerability details

When decoding an integer from ASN.1, a precondition error occurs in the BigInt library and thus a crash occurs if the integer has a length of 0.
For example, the following test case tries to parse an integer with a length of 0:
```
func testZeroLength() throws {
    let b1: Bytes = [2, 0] // Integer of zero length try ASN1.build(b1)
}
```
The ASN1 library does not consider this case [1]:
```
public init(_ bytes: Bytes) { 
    self.asBytes = bytes
    self.value = BInt(signed: bytes) 
    super.init(ASN1.TAG_Integer)
}
```
This causes a precondition error in the BigInt library:
```
BigInt/BigInt.swift:208: Precondition failed: Empty byte array 
Current stack trace:
0 libswiftCore.so 0x00007fb45096c210 swift_reportError + 50
1 libswiftCore.so 0x00007fb4509e0fc0 _swift_stdlib_reportFatalErrorInFile + 112
2 libswiftCore.so 0x00007fb4506c9c40 _assertionFailure(_:_:file:line:flags:) + 1329
[...]
```
## Countermeasures
We recommend validating the length and throwing an exception if necessary. Possibly, the BigInt library should throw the exception itself to avoid crashes in other deployment locations as well.

## References
[1] Source code of the constructor of the ASN1Integer class: https://github.com/leif-ibsen/ASN1/blob/53e0b34a34f882386e09d10d6d00bb7e969e307f/Sources/ASN1/ASN1Integer.swift#L19

**Comment by leif-ibsen** [comment]
Fixed in release 2.0.0. ASN1Integer now throws if given empty input
