### ISSUE TITLE
Crypto Review Finding #7: Integer Overflow Crash in ASN1ObjectIdentifier

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/ASN1#5]
## Vulnerability details

When decoding an object identifier from ASN.1, an integer overflow error and thus a crash occurs if individual parts of the object identifier are too large.
For example, the following test case tries to parse the Object Identifier 6.15.1180591620717411303423:

```
func testOIDOverflow() throws {
  let b1: Bytes = [6, 11, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255] // Object Identifier = 6.15.1180591620717411303423 
  try ASN1.build(b1)
}
```
The ASN1 library does not consider this case and an integer overflow error may occur in line 9 [1]:

```
static func bytes2oid(_ bytes: Bytes) -> String {
    if bytes.count == 0 {
        return ""
    }
    var sb = (bytes[0] / 40).description + "." + (bytes[0] % 40).description
    var size = 2
    var l = 0
    for i in 1 ..< bytes.count { 
        l*=128
        l += Int(bytes[i] & 0x7f) 
        if bytes[i] < 128 {
            sb.append("." + l.description) 
            l=0
            size += 1
            } 
    }
    return sb
}
```
The integer overflow error causes Swift to terminate the program:
```
 Test Case 'ASN1Tests.testOIDOverflow' started at 2021-07-01 11:22:13.161 Exited with signal code 4
```

## Countermeasures
We recommend checking for an integer overflow and throwing an exception if necessary. This can happen for example via the function multipliedReportingOverflow:
```
let overflow: Bool
(l, overflow) = l.multipliedReportingOverflow(by: 128) 
if overflow {
    throw /* some ASN1Exception */ 
}
```

## References
[1] Source coder of the function bytes2oid in the class ASN1ObjectIdentifier: https://github.com/leif-ib- sen/ASN1/blob/53e0b34a34f882386e09d10d6d00bb7e969e307f/Sources/ASN1/ASN1Obj ectIdentifier.swift#L97

**Comment by leif-ibsen** [comment]
Fixed in release 2.0.0. Integer arithmetic is now done using BInt's
