### ISSUE TITLE
Crypto Review Finding #8: Integer overflow on 32-bit systems

### ISSUE THREAD

**Issue by lorenz-loesch-ynx** [leif-ibsen/ASN1#6]
## Vulnerability details
When decoding the ASN.1 length field, an integer overflow can occur on 32-bit systems.
The length is stored in the function getLength in a variable of type Int [1], which is signed. Thus, in principle, negative values can also be stored. In Swift, Int can correspond to either Int32 or Int64, depending on the CPU architecture.
When parsing the length, a maximum of four values of type UInt8 are read and then the length in the Int variable is calculated using Left Shift (lines 11 to 17). On a 32-bit system this can also set the highest bit of the Int32 variable, which results in an integer overflow and the entire length results in a negative value.

```
static func getLength(_ input: InputStream) throws -> Int {
    var length: Int
    let nb = try input.nextByte() if nb < 128 {
        length = Int(nb)
    } else {
        [...]
        let lb = nb & 0x7f
        if lb == 0 {
[...]
        } else if lb == 4 {
            length = Int(try input.nextByte())
            length <<= 8
            length |= Int(try input.nextByte()) length <<= 8
            length |= Int(try input.nextByte()) length <<= 8
            length |= Int(try input.nextByte())
        } else {
            throw ASN1Exception.tooLong(position: input.getPosition(), length: Int(lb)) 
        }
     }
    return length  
 }
```
## Countermeasures
The integer overflow should be prevented. Either a sufficiently large variable type can be used (Int64 also on 32-bit systems) or alternatively the processing of such large data on 32-bit systems can be denied and an exception thrown.

## References
[1] Source coder of the function getLength in the class ASN1: https://github.com/leif-ibsen/ASN1/blob/53e0b34a34f882386e09d10d6d00bb7e969e307f/Sources/ASN1/ASN1.swift#L243

**Comment by leif-ibsen** [comment]
Fixed in release 2.0.0. Integer arithmetic is now done using BInt's
